name: "Deploy site"
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_site:
    name: "Build site"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4.1.1
        with:
          submodules: true
          lfs: true
      - name: Build only
        uses: shalzz/zola-deploy-action@v0.18.0
        env:
          BUILD_DIR: ./
          BUILD_ONLY: true
          BUILD_THEMES: true
      - name: push to s3 bucket
        uses: ctrlok/scw-s3-action@v0.0.4
        with:
          args: s3 sync public/ s3://${{ secrets.S3_BUCKET }}/
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_REGION: "fr-par"
